kind: pipeline
type: docker
name: default
platform:
    os:   linux
    arch: arm64

volumes:
    -   name: cache
        host:
            path: /mnt/datahdd/drone/cache
    -   name: docker
        host:
            path: /var/run/docker.sock

trigger:
    event: [ push, pull_request ]
    branch: [ main ]

steps:
    -   name:  restore cache
        image: meltwater/drone-cache
        settings:
            backend: "filesystem"
            restore: true
            mount:
                - 'node_modules'
        volumes:
            -   name: cache
                path: /tmp/cache

    -   name:  .npmrc
        image: busybox
        environment:
            GITHUB_TOKEN:
                from_secret: GITHUB_TOKEN
            NPM_TOKEN:
                from_secret: NPM_TOKEN
            NPM_EMAIL:
                from_secret: NPM_EMAIL
        commands:
#            - echo "@dasred:registry=https://npm.pkg.github.com/" > .npmrc
#            - echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> .npmrc
            - echo "_auth=$NPM_TOKEN" > .npmrc
            - echo "email=$NPM_EMAIL" >> .npmrc
            - echo "always-auth=true" >> .npmrc

    -   name:  npm install
        image: node:18-alpine
        commands:
            - npm i

    -   name:  publish
        image: node:18-alpine
        commands:
            - apk update && apk upgrade && apk add git
            - npm run publish

    -   name:  rebuild cache
        image: meltwater/drone-cache
        settings:
            backend: "filesystem"
            rebuild: true
            mount:
                - 'node_modules'
        volumes:
            -   name: cache
                path: /tmp/cache
        when:
            status:
                - success
                - failure
