kind: pipeline
type: docker
name: default
platform:
    os:   linux
    arch: arm64

volumes:
    -   name: cache
        host:
            path: /mnt/datahdd/drone/cache
    -   name: docker
        host:
            path: /var/run/docker.sock

trigger:
    event: [ push, pull_request ]
    branch: [ main ]

steps:
    -   name:  restore cache
        image: meltwater/drone-cache
        settings:
            backend: "filesystem"
            restore: true
            mount:
                - 'node_modules'
        volumes:
            -   name: cache
                path: /tmp/cache

    -   name:  publish
        image: node:18-alpine
        environment:
            GH_TOKEN:
                from_secret: GH_TOKEN
            NPM_TOKEN:
                from_secret: NPM_TOKEN
        commands:
            - apk update && apk upgrade && apk add git
            - npm i
            - npm run semantic-release

    -   name:  rebuild cache
        image: meltwater/drone-cache
        settings:
            backend: "filesystem"
            rebuild: true
            mount:
                - 'node_modules'
        volumes:
            -   name: cache
                path: /tmp/cache
        when:
            status:
                - success
                - failure
